services:

  mysql:

    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: NewPassword123
      MYSQL_DATABASE: librarydb

    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  flaskapp:

    build: ./app

    restart: always

    ports:
      - "5010:5000"

    depends_on:
      - mysql